unified_prompt: "Remember the following content chunk by completing these steps:\n\n1. **Core Memory Update**: Maintain an understanding of the user, or a summary of what the user is reading, or a set of classification rules summarized from the classification examples (label 1: meaning; label 2: meaning, etc.). Keep updates brief (a few sentences maximum).\n\n2. **Memory Storage**:\n   - **Episodic Memory**: Record user actions, user's friends' actions and assistant actions with timestamps (format: \"At timestamp t, user did X\")\n   - **Semantic Memory**: Record key facts and information (format: \"John is User's 18-year-old friend\", \"Harry Potter author: J.K. Rowling\", \"Sample: xxx; Label: xxx\")\n\n<new_chunk>\n{context}\n</new_chunk>\n\n**Important**: Response limit is {max_new_tokens} tokens. Be concise and brief in all memory updates."

squad:
    query_prompt: null
    including_core: true

hotpotqa:
    query_prompt: null
    including_core: true

booksum:
    query_prompt: "Your core memory contains a comprehensive book summary. Use this information to fulfill the user's request."
    including_core: true

pubmed-rct:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true

ttl_train:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Your semantic memory likely includes example labels. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true

perltqa:
    query_prompt: null
    including_core: true

lme_train:
    query_prompt: null
    including_core: true

accurate_retrieval:
    query_prompt: null
    including_core: true

ruler_qa1_197K:
    query_prompt: null
    including_core: true

ruler_qa2_421K:
    query_prompt: null
    including_core: true

infbench_qa_eng_shots2:
    query_prompt: "The book has been memorized in the memory. Answer the question as briefly as possible. Only output the answer with no other text."
    including_core: true

longmemeval_s*:
    query_prompt: null
    including_core: true

long_range_understanding:
    query_prompt: "Your core memory contains a comprehensive book summary. Use this information to fulfill the user's request."
    including_core: true

test_time_learning:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Your semantic memory likely includes example labels. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true


icl_banking77_5900shot_balance:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Your semantic memory likely includes example labels. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true

icl_clinic150_7050shot_balance:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Your semantic memory likely includes example labels. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true

icl_nlu_8296shot_balance:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Your semantic memory likely includes example labels. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true

icl_trec_coarse_6600shot_balance:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true

icl_trec_fine_6400shot_balance:
    query_prompt: "Your core memory is used to store the classification rules of the articles. Identify the meaning of each class and how the article is classified. Fulfill the user's request with the core memory.\n\nWhen answering questions, you should put the final prediction in the format of \\boxed{label}. Note that the label is a single number."
    including_core: true
